004 view band roles
Andrewwango/kainosRecruitmentUi-TeamA pull request #11
Opened 2022-10-03 13:56 UTC by JennicaMistry

Added the ID tags to the Band html page and make sure the band UI tests function

2022-10-03 15:10 UTC, hellofadude requested changes
You should not be committing files in node_modules folder. ATM it says you're trying to commit 5000 plus changes. Please remove changes to node_modules folder and resubmit.

2022-10-04 09:34 UTC, shaunganley requested changes

2022-10-04 09:34 UTC, shaunganley commented on app/interface.js
> +        const response = await axios.get('http://localhost:8080/api/viewBandLevel');
shouldn't hardcode localhost, store in an environment variable instead

2022-10-04 14:06 UTC, shaunganley requested changes

2022-10-04 14:06 UTC, shaunganley commented on app/config.js
> +  bandLevel: process.env.BAND_LEVEL
don't pass in the entire URL, pass in the base URl then append the specific route to each endpoint in the code

2022-10-04 14:06 UTC, shaunganley commented on package.json
> -{
these files shouldn't have been deleted?

2022-10-04 14:24 UTC, shaunganley approved these changes

2022-10-04 14:29 UTC, hellofadude approved these changes

2022-10-04 14:30 UTC, merged